graph_file: 'data/course3_edge.csv'
test_file: 'data/course3_test.csv'
checkpoint_dir: 'checkpoint'
walking_pool_size: 40
num_walks: 40
walk_length: 20
embedding_dim: 256
epoch_num: 300
batch_size: 128
learning_rate: 0.01
milestones: [100]
gamma: 0.1
p: 0.5
q: 2
k: 30
